apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-poc
  namespace: api-poc
  labels:
    io.kompose.service: api-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-poc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: api-poc
    spec:
      containers:
        - name: api-poc
          image: juniorssalvador/api-poc
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: ged
spec:
  type: NodePort
  ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
