"""empty message

Revision ID: c5223adc1a2f
Revises: 
Create Date: 2022-04-11 16:00:05.685929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5223adc1a2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='kd_o_bonde'
    )
    op.create_table('onibus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('lotacao', sa.Integer(), nullable=True),
    sa.Column('linha_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['linha_id'], ['kd_o_bonde.linha.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kd_o_bonde'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onibus', schema='kd_o_bonde')
    op.drop_table('linha', schema='kd_o_bonde')
    # ### end Alembic commands ###
